### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ImDayy** [Fluto/Taiko-no-Tatsujin-The-Drum-Master-Patch#1]
I have tried both patches the old and new one and I still cant seem to get it to pop up. I already reinstalled everything and have tried mutiple times, downloading BepInEx, dragging it to taiko's folder, opening taiko, closing it, opening plugins folder dragging the dll and opening again and after loading up and showing the autosave warning my screen flashes and it takes me instantly to the menu screen asking me to sign in. Here's a video showing whats happening, hope anyone can help me fix this

https://user-images.githubusercontent.com/98785909/151892287-937a2adb-ac79-45af-86f5-cf33286df830.mp4

**Comment by Fluto** [comment]
Just to confirm, are you using `BepInEx_x64_5.4.18.0` ? 
Can you post the log at `.\BepInEx\LogOutput.log`? 

Perhaps there will be something in there that can help me

**Comment by ImDayy** [comment]
I am using BepInEx_x64_5.4.18.0 as shown in the image: 
![image](https://user-images.githubusercontent.com/98785909/151901095-09cffb10-2bd5-4327-a940-30c5163d5bec.png)

and here is the log
[LogOutput.log](https://github.com/Fluto/Taiko-no-Tatsujin-The-Drum-Master-Patch/files/7975325/LogOutput.log)

**Comment by Fluto** [comment]
Strange, it says that it's loading in the logs.
Can you post:
`.\BepInEx\config\BepInEx.cfg`
`.\BepInEx\config\com.fluto.taikomods.cfg`

It seems to be a problem with BepInEx...? Im not too familiar with the nuances of it.

**Comment by ImDayy** [comment]
There is no `.\BepInEx\config\com.fluto.taikomods.cfg`
But there is  `BepInEx.cfg`
https://file.io/2LliUUZ3dmFU
Had to do a file.io since I cant share .cfg files

**Comment by Fluto** [comment]
Ah, it appears you need to enable logs (I forgot about that) can you enable logs at 
```
[Logging.Console]

## Enables showing a console for log output.
# Setting type: Boolean
# Default value: false
Enabled = false
```
Set that to true
`Enabled = false`

Launch the game
Then post the logs again? Perhaps there will be more information for me that way

**Comment by ImDayy** [comment]
Apparently the game is no longer moddable and its not letting me do any changes???
![image](https://user-images.githubusercontent.com/98785909/151902774-cc6ae100-4fd9-4b0a-bd82-e6391d76324c.png)

**Comment by Fluto** [comment]
Seems like an update just rolled out
![image](https://user-images.githubusercontent.com/7686594/151902906-e95b2d6b-d399-49dd-b920-f0d63037419e.png)

**Comment by ImDayy** [comment]
Can't seem to find the update or my game updated by itself.

edit: reinstalling

**Comment by Arkendo1** [comment]
It just now fixed the launch issue

**Comment by ImDayy** [comment]
It still aint working for me, apparently its an issue on my end :(
